version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: contacts
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
